/**
 * @file rrc_coefficients.h
 * @brief Root-Raised Cosine Filter Coefficients for FPGA Implementation
 *
 * COSPAS-SARSAT T.018 OQPSK Modulation - PlutoSDR FPGA Integration
 *
 * Parameters:
 * - Chip rate: 38.4 kchips/s
 * - Sample rate: 400 kHz
 * - Samples/chip: ~10.42
 * - Roll-off (α): 0.8
 * - Filter taps: 63 (odd for symmetry)
 * - Format: Q15 (16-bit signed fixed-point)
 *
 * Generated by: generate_rrc.py
 * Date: 2025-10-18
 *
 * Usage:
 * - C/C++ simulation: Include this header directly
 * - VHDL implementation: Copy coefficients to VHDL array declaration
 */

#ifndef RRC_COEFFICIENTS_H
#define RRC_COEFFICIENTS_H

#include <stdint.h>

// =============================================================================
// FILTER PARAMETERS
// =============================================================================

#define RRC_NUM_TAPS        63      // Number of filter taps (must be odd)
#define RRC_ROLLOFF         0.8f    // Roll-off factor (α)
#define RRC_CENTER_TAP      31      // Center tap index (symmetric filter)

// Format specifications
#define RRC_COEFF_BITS      16      // Coefficient width (Q15 format)
#define RRC_COEFF_FRAC      15      // Fractional bits in Q15
#define RRC_INPUT_BITS      12      // PlutoSDR DAC resolution
#define RRC_OUTPUT_BITS     12      // PlutoSDR DAC resolution

// =============================================================================
// RRC FILTER COEFFICIENTS (Q15 FORMAT)
// =============================================================================

/**
 * RRC filter coefficients in Q15 fixed-point format
 *
 * Q15 format: 1 sign bit + 15 fractional bits
 * Range: -32768 to +32767 representing -1.0 to +0.999969
 *
 * For VHDL conversion, use:
 *   type coeff_array is array (0 to 62) of signed(15 downto 0);
 *   constant RRC_COEFFS : coeff_array := (
 *     0  => to_signed(32767, 16),
 *     1  => to_signed(-2943, 16),
 *     ...
 *   );
 */
static const int16_t rrc_coefficients[RRC_NUM_TAPS] = {
    // Tap 0-7
    32767, -2943,  -314,    63,   128,   107,    63,    19,

    // Tap 8-15
      -11,   -26,   -27,   -18,    -6,     5,    11,    12,

    // Tap 16-23
        9,     3,    -2,    -6,    -7,    -5,    -2,     1,

    // Tap 24-31 (center region)
        4,     4,     3,     1,    -1,    -3,    -3,    -2,

    // Tap 32-39 (symmetric continuation)
       -1,     1,     2,     2,     2,     1,    -1,    -1,

    // Tap 40-47
       -2,    -1,     0,     0,     1,     1,     1,     0,

    // Tap 48-55
        0,    -1,    -1,    -1,     0,     0,     1,     1,

    // Tap 56-62
        1,     0,     0,    -1,    -1,    -1,     0
};

// =============================================================================
// HELPER MACROS FOR VHDL CONVERSION
// =============================================================================

/**
 * Example VHDL entity declaration for RRC filter module:
 *
 * entity rrc_filter is
 *   Port (
 *     clk       : in  std_logic;
 *     reset     : in  std_logic;
 *     data_in   : in  signed(11 downto 0);   -- Q11 input (12-bit)
 *     data_out  : out signed(11 downto 0)    -- Q11 output (12-bit)
 *   );
 * end rrc_filter;
 *
 * architecture Behavioral of rrc_filter is
 *   type coeff_array is array (0 to 62) of signed(15 downto 0);
 *   constant RRC_COEFFS : coeff_array := (
 *     -- Copy coefficients from rrc_coefficients[] array above
 *     0  => to_signed(32767, 16),
 *     1  => to_signed(-2943, 16),
 *     2  => to_signed(-314, 16),
 *     -- ... (continue for all 63 taps)
 *     62 => to_signed(0, 16)
 *   );
 *
 *   -- Shift register for input samples
 *   type shift_reg_array is array (0 to 62) of signed(11 downto 0);
 *   signal shift_reg : shift_reg_array := (others => (others => '0'));
 *
 *   -- Accumulator for MAC operation (Q26 = Q11 * Q15)
 *   signal accumulator : signed(31 downto 0);
 *
 * begin
 *   -- FIR filter implementation (see rrc_filter.vhd)
 * end Behavioral;
 */

// =============================================================================
// COEFFICIENT STATISTICS (FOR VERIFICATION)
// =============================================================================

/**
 * Coefficient statistics:
 * - Min value: -2943 (Q15 ≈ -0.0898)
 * - Max value: 32767 (Q15 ≈ +0.9997)
 * - Center tap (31): -2 (Q15 ≈ -0.00006)
 * - Symmetry: Filter is symmetric (phase-linear)
 * - DC gain: Sum of coefficients ≈ 32767 (normalized to 1.0)
 *
 * Expected frequency response:
 * - Pass-band: 0 to ~19.2 kHz (chip_rate / 2)
 * - Transition: 19.2 to 34.56 kHz (roll-off region)
 * - Stop-band: > 34.56 kHz (attenuated)
 */

#endif // RRC_COEFFICIENTS_H
